"use client";

import { useEffect, useState } from "react";
import { Heart, Mail } from "lucide-react";
import { PlanResult, predictCrowd, CrowdResult, getPackingChecklist, saveTrip, addFavorite } from "@/lib/api";
import { VoiceOutputButton } from "@/components/VoiceInput";

function buildEmailSummary(result: PlanResult): { subject: string; body: string } {
  const subject = `Trip Summary — ${result.destination}`;
  const body = [
    `Trip Summary`,
    ``,
    `Destination: ${result.destination}`,
    `Duration: ${result.trip_summary}`,
    `Travel Mode: ${result.transport_mode}`,
    result.flight ? `Travel: ${result.flight.airline || result.flight.label} — ₹${result.flight.price}` : "",
    `Hotel: ${result.hotel.name} — ₹${result.hotel.price_per_night}/night`,
    `Total Cost: ₹${result.total_cost.toLocaleString("en-IN")} (Budget ₹${result.budget.toLocaleString("en-IN")})`,
    `Weather: ${result.weather.condition}, ${result.weather.temp_c}°C`,
    ``,
    `Generated by Trip Agent (prototype).`,
  ].filter(Boolean).join("\n");
  return { subject, body };
}

export default function TripExtras({ result, loggedIn }: { result: PlanResult; loggedIn: boolean }) {
  const [crowd, setCrowd] = useState<CrowdResult | null>(null);
  const [packing, setPacking] = useState<string[]>([]);
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [favoriteStatus, setFavoriteStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");

  useEffect(() => {
    predictCrowd(result.destination).then(setCrowd).catch(() => undefined);
    getPackingChecklist(result.destination, result.weather.condition, 3)
      .then((r) => setPacking(r.items))
      .catch(() => undefined);
  }, [result.destination, result.weather.condition]);

  async function handleSave() {
    if (!loggedIn) return;
    setSaveStatus("saving");
    try {
      await saveTrip(result.session_id, result.destination, result.budget, result.total_cost, result);
      setSaveStatus("saved");
    } catch {
      setSaveStatus("error");
    }
  }

  async function handleFavorite() {
    if (!loggedIn) return;
    setFavoriteStatus("saving");
    try {
      await addFavorite({
        name: result.destination,
        destination: result.destination,
        category: "destination",
        lat: result.route?.center.lat || null,
        lng: result.route?.center.lng || null,
      });
      setFavoriteStatus("saved");
    } catch {
      setFavoriteStatus("error");
    }
  }

  const { subject, body } = buildEmailSummary(result);
  const mailtoHref = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

  return (
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <div className="glass card-hover rounded-xl p-4">
        <div className="flex items-center justify-between mb-2">
          <p className="text-xs uppercase tracking-[0.2em] text-mist">Crowd Prediction</p>
        </div>
        {crowd ? (
          <>
            <p className="text-sm font-semibold text-amber">{crowd.level}</p>
            <p className="text-xs text-mist mt-1">{crowd.advice}</p>
          </>
        ) : (
          <div className="skeleton h-10" />
        )}
      </div>

      <div className="glass card-hover rounded-xl p-4">
        <p className="text-xs uppercase tracking-[0.2em] text-mist mb-2">Packing Checklist</p>
        <ul className="text-sm space-y-0.5 max-h-32 overflow-y-auto">
          {packing.length ? packing.map((item) => <li key={item}>· {item}</li>) : <div className="skeleton h-10" />}
        </ul>
      </div>

      <div className="glass card-hover rounded-xl p-4 flex flex-col justify-between gap-3">
        <div className="flex items-center justify-between">
          <p className="text-xs uppercase tracking-[0.2em] text-mist">Trip Summary</p>
          <div className="flex items-center gap-2">
            <a href={mailtoHref} title="Email this trip summary" className="text-mist hover:text-amber transition">
              <Mail size={15} />
            </a>
            <VoiceOutputButton text={result.trip_summary} />
          </div>
        </div>
        {loggedIn ? (
          <div className="grid grid-cols-1 gap-2">
            <button onClick={handleSave} disabled={saveStatus === "saving" || saveStatus === "saved"} className="text-sm bg-amber text-ink font-semibold rounded-xl py-2 disabled:opacity-60">
              {saveStatus === "saved" ? "Saved to Trip History ✓" : saveStatus === "saving" ? "Saving…" : "Save this Trip"}
            </button>
            <button onClick={handleFavorite} disabled={favoriteStatus === "saving" || favoriteStatus === "saved"} className="text-sm border border-line px-4 py-2 rounded-xl hover:border-gold/40 hover:text-gold transition disabled:opacity-60 flex items-center justify-center gap-1.5">
              <Heart size={14} className={favoriteStatus === "saved" ? "text-alert fill-current" : ""} />
              {favoriteStatus === "saved" ? "Saved to Favorites ✓" : favoriteStatus === "saving" ? "Saving Favorite…" : "Add to Favorites"}
            </button>
          </div>
        ) : (
          <p className="text-xs text-mist">Sign in to save this trip to your history.</p>
        )}
        {(saveStatus === "error" || favoriteStatus === "error") && <p className="text-xs text-alert">Could not save your selection.</p>}
      </div>
    </div>
  );
}
